---

- set_fact:
    users_to_sudoers:
      - karl

- name: Configuration | Accounts | Sudoers | Touch sudoer file
  file:
    path: "/etc/sudoers.d/{{ item }}"
    state: touch
    mode: g=r,o=r
  with_items: "{{ users_to_add }}"
  changed_when: false

- name: Configuration | Accounts | Sudoers | Configure sudoer file
  lineinfile: 
    dest: "/etc/sudoers.d/{{ item }}"
    line: "{{ item }} ALL=(ALL) ALL"
  with_items: "{{ users_to_sudoers }}"