---

- name: Xorg | Video Drivers | Install packages
  aur:
    use: yay
    name:
      - nvidia
      - nvidia-settings
      - nvidia-utils
      - lib32-nvidia-utils
      - lib32-opencl-nvidia
      - opencl-nvidia
      - libvdpau
      - libxnvctrl
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - gamemode