---

- name: Yay | Check
  stat:
    path: /usr/bin/yay
  register: yay_binary
  changed_when: false
  failed_when: false

- name: Yay | Install
  become: yes
  become_user: aur_builder
  aur:
    name: yay-bin
  when: not yay_binary.stat.exists

- name: Yay | Configure
  aur:
    use: yay
    name:
      - bash
      - ca-certificates-mozilla
      - gcc-libs
      - glib2
      - glibc
      - gmp
      - gnutls
      - hwids
      - iana-etc
      - libarchive
      - libcap
      - libgpg-error
      - libldap
      - libtasn1
      - linux-api-headers
      - ncurses
      - pacman-mirrorlist
      - readline
      - shadow
      - systemd
      - systemd-libs
  when: not yay_binary.stat.exists