---

- name: Yay | Check
  stat:
    path: /usr/bin/yay
  register: yay_binary
  changed_when: false
  failed_when: false

- name: Yay | Install
  become: yes
  become_user: aur_builder
  aur:
    name: yay-bin
  when: not yay_binary.stat.exists
