---

- name: Include setup tasks
  include: tasks/setup.yml

- name: Include account configuration tasks
  include: tasks/config/accounts/main.yml

- name: Include mirror tasks
  include: tasks/config/mirrors.yml

- name: Include tasks for archfi & archdi
  include: tasks/install/archibins.yml

- name: Include package management installation tasks
  include: tasks/install/packages/main.yml

- name: Include desktop installation tasks
  include: tasks/install/desktop/main.yml

- name: Include cleanup tasks
  include: tasks/cleanup.yml
