---

- name: Package Install/Update
  aur:
    use: yay
    name:
      # dev
      - code
      - goland
      - phpstorm
      - webstorm
      # graphic
      # internet/webbrowser
      - firefox
      # multimedia/videoplayer
      - vlc
      # system/system
      - wine



      # games
      - wolf-data-steam
      - wolf3d-data-steam
      # games/other
      - nvidia
      - nvidia-settings
      - nvidia-utils
      - lib32-nvidia-utils
      - lib32-opencl-nvidia
      - opencl-nvidia
      - libvdpau
      - libxnvctrl
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - gamemode
      - steam