---

- name: Install | Console | Recovery
  become: yes
  become_user: aur_builder
  aur:
    use: "{{ package_manager|default('yay') }}"
    name: "{{ item }}"
  with_items:
    - ddrescue
    - dd_rescue
    - partclone