---

- name: Archdi | Check
  stat:
    path: /usr/local/bin/archdi
  register: archdi_stat
  changed_when: false

- name: Archdi | Download
  get_url:
    url: http://archdi.sf.net/archdi
    dest: /tmp/archdi
    mode: '0700'
  changed_when: false

- name: Archdi | Checking version
  command: diff /usr/local/bin/archdi /tmp/archdi
  register: archdi_version_check
  when: not archdi_stat.stat.exists
  changed_when: false
  failed_when: false

- name: Archdi | Dependencies
  pacman:
    name:
      - gpm
      - slang
      - arch-install-scripts
    state: present
  when: not archdi_stat.stat.exists

- name: Archdi | Install
  copy:
    remote_src: True
    src: /tmp/archdi
    dest: /usr/local/bin/archdi
  when: archdi_version_check.failed