---

- name: Archfi | Check
  stat:
    path: /usr/local/bin/archfi
  register: archfi_stat
  changed_when: false

- name: Archfi | Download
  get_url:
    url: http://archfi.sf.net/archfi
    dest: /tmp/archfi
    mode: '0700'
  changed_when: false

- name: Archdi | Checking version
  command: diff /usr/local/bin/archfi /tmp/archfi
  register: archfi_version_check
  when: not archfi_stat.stat.exists
  changed_when: false
  failed_when: false

- name: Archfi | Dependencies
  pacman:
    name:
      - libnewt
      - wget
    state: present
  when:
    - not archfi_stat.stat.exists

- name: Archfi | Install
  copy:
    remote_src: True
    src: /tmp/archfi
    dest: /usr/local/bin/archfi
  when: archfi_version_check.failed