---

- set_fact:
    users_to_add:
      - karl
      

- name: Configuration | Accounts | Users | Create
  user:
    name: "{{ item }}"
    home: "{{ item }}"
    state: present
  with_items: "{{ users_to_add }}"
  failed_when: false
