---

- name: Display Manager | Gnome | Install
  aur:
    use: yay
    name:
      - gnome
      - gnome-extra

- name: Display Manager | Plasma | Disable Display Managers
  service:
    name: "{{ item }}"
    enabled: no
  ignore_errors: yes
  with_items:
    - lightdm
    - lxdm
    - sddm

- name: Display Manager | Gnome | Enable GDM
  service:
    name: gdm
    enabled: yes