---

# https://github.com/erikdubois/Archi3/tree/master/installation

- name: Display Manager | i3wm | Install
  aur:
    use: "{{ package_manager|default('yay') }}"
    name:
#      - virtualbox-guest-utils ?
      - i3lock
      - i3status
      - j4-dmenu-desktop
      - packer
      - i3blocks
      - i3-gaps-next-git
      - archey3
      - baobab
      - bleachbit
      - catfish
      - clementine
      - conky
      - curl
      - darktable
      - dconf-editor
      - dmidecode
      - evince
      - evolution
      - filezilla
      - firefox
      - galculator
      - geary
      - gimp
      - git
      - gksu
      - glances
      - gnome-disk-utility
      - gnome-font-viewer
      - gnome-screenshot
      - gnome-system-monitor
      - gnome-terminal
      - gnome-tweak-tool
      - gparted
      - gpick
      - grsync
      - hardinfo
      - hddtemp
      - hexchat
      - htop
      - inkscape
      - inxi
      - lm_sensors
      - lsb-release
      - meld
      - mlocate
      - mpv
      - nemo
      - net-tools
      - numlockx
      - openshot
      - pinta
      - plank
      - polkit-gnome
      - redshift
      - ristretto
      - sane
      - screenfetch
      - scrot
      - shotwell
      - simple-scan
      - simplescreenrecorder
      - smplayer
      - sysstat
      - terminator
      - thunar
      - transmission-cli
      - transmission-gtk
      - variety
      - vlc
      - vnstat
      - wget
      - unclutter
      - unace
      - unrar
      - zip
      - unzip
      - sharutils
      - uudeview
      - arj
      - cabextract
      - file-roller
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
      - alsa-utils
      - alsa-plugins
      - alsa-lib
      - alsa-firmware
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-base
      - gst-plugins-ugly
      - gstreamer


- name: Display Manager | i3wm | Clone
  git:
    repo: https://github.com/erikdubois/Archi3.git
    dest: /tmp/archi3

- name: Display Manager | i3wm | Run scripts
  command: "./installation/{{ item }}.sh"
  args:
    chdir: /tmp/archi3
  with_items:

#    - 030-install-xorg-ati TODO
#    - 030-install-xorg-intel TODO
#    - 030-install-xorg-nvidia DONE ELSEWHERE
#    - 030-install-xorg-virtualbox

#    - 200-install-extra-software-v1 TODO
#    - 300-install-themes-icons-cursors-conky-v1 TODO
#    - 400-install-software-distro-specific-v1 TODO
#    - 500-install-samba-v1 TODO

#    - 600-install-personal-settings-folders-v1 TODO
#    - 610-install-personal-settings-gimp-v1 TODO
#    - 620-install-personal-settings-arc-colora-v1 TODO
#    - 630-install-personal-settings-variety-v1 TODO
#    - 640-install-personal-settings-root-files-v1 TODO
#    - 650-install-personal-settings-gnome-screenshot-v1 TODO ?

#    - 690-install-personal-settings-i3-configuration-v1 TODO
#    - 700-firefox-for-dark-themes-settings-v1 TODO