---

- name: Display Manager | LXDE-GTK3 | Install
  aur:
    use: yay
    name:
      - lxde-gtk3

- name: Display Manager | LXDE-GTK3 | Disable Display Managers
  service:
    name: "{{ item }}"
    enabled: no
  ignore_errors: yes
  with_items:
    - gdm
    - lightdm
    - sddm

- name: Display Manager | LXDE-GTK3 | Enable LXDM
  service:
    name: lxdm
    enabled: yes