---

- name: Display Manager | LXDE | Install
  aur:
    use: "{{ package_manager|default('yay') }}"
    name:
      - lxde

- name: Display Manager | Plasma | Disable Display Managers
  service:
    name: "{{ item }}"
    enabled: no
  ignore_errors: yes
  with_items:
    - gdm
    - lightdm
    - sddm

- name: Display Manager | LXDE | Enable LXDM
  service:
    name: lxdm
    enabled: yes