---

- name: Display Manager | LXDE | Install
  aur:
    use: yay
    name:
      - lxde

- name: Display Manager | Plasma | Disable Display Managers
  service:
    name: gdm
    state: disabled
  ignore_errors: yes
  with_items:
    - gdm
    - lightdm
    - sddm

- name: Display Manager | LXDE | Enable LXDM
  service:
    name: lxdm
    state: enabled