---

- name: Display Manager | LXQT | Install
  aur:
    use: "{{ package_manager|default('yay') }}"
    name:
      - lxqt

- name: Display Manager | LXQT | Install Complements
  aur:
    use: "{{ package_manager|default('yay') }}"
    name:
      - sddm
      - oxygen-icons
      - connman
      - obconf
      - lxqt-connman-applet-git

- name: Display Manager | LXQT | Disable Display Managers
  service:
    name: "{{ item }}"
    enabled: no
  ignore_errors: yes
  with_items:
    - gdm
    - lightdm
    - lxdm

- name: Display Manager | LXQT | Enable SDDM
  service:
    name: sddm
    enabled: yes