---

- name: Display Manager | MaterialAwesome | Install
  become: yes
  become_user: aur_builder
  aur:
    use: "{{ package_manager|default('yay') }}"
    name:
      - awesome
      - ttf-roboto
      - rofi
      - compton
      - i3lock-fancy
      - xclip
      - pa-applet-git
      - materia-gtk-theme
      - papirus-icon-theme
      - lxappearance
      - qt5-styleplugins

- name: Display Manager | MaterialAwesome | Configure
  git:
    repo: https://github.com/ChrisTitusTech/material-awesome.git
    dest: ~/.config/awesome

- name: Display Manager | MaterialAwesome | Environment
  lineinfile:
    path: /etc/environment
    regexp: "{{ item }}"
    line: "{{ item }}"
  with_items:
    - 'XDG_CURRENT_DESKTOP=Unity'
    - 'QT_QPA_PLATFORMTHEME=gtk2'

# gnome-keyring-daemon, policykit-agent, qt5-styles-gtk2, kde-spectacle