---

- name: Display Manager | Plasma | Install
  aur:
    use: yay
    name:
      - plasma
      - bluedevil
      - breeze
      - breeze-gtk
      - discover
      - drkonqi
      - kactivitymanagerd
      - kde-cli-tools
      - kde-gtk-config
      - kdecoration
      - kdeplasma-addons
      - kgamma5
      - khotkeys
      - kinfocenter
      - kmenuedit
      - knetattach
      - kscreen
      - kscreenlocker
      - ksshaskpass
      - ksysguard
      - kwallet-pam
      - kwayland-integration
      - kwin
      - kwrited
      - libkscreen
      - libksysguard
      - milou
      - oxygen
      - plasma-browser-integration
      - plasma-desktop
      - plasma-integration
      - plasma-nm
      - plasma-pa
      - plasma-sdk
      - plasma-thunderbolt
      - plasma-vault
      - plasma-workspace
      - plasma-workspace-wallpapers
      - polkit-kde-agent
      - powerdevil
      - sddm-kcm
      - systemsettings
      - user-manager
      - xdg-desktop-portal-kde

- name: Display Manager | Plasma | Disable Display Managers
  service:
    name: gdm
    state: disabled
  ignore_errors: yes
  with_items:
    - gdm
    - lightdm
    - lxdm

- name: Display Manager | Plasma | Enable SDDM
  service:
    name: sddm
    state: enabled