---

- name: Install | Compression
  become: yes
  become_user: aur_builder
  aur:
    use: "{{ package_manager|default('yay') }}"
    name: "{{ item }}"
  with_items:
    - zip
    - unzip
    - unrar
    - p7zip
    - lzop